Feature/newsletter add image
ThyArt/thyart-api pull request #39
Opened 2019-11-24 13:13 UTC by CorvinAlex

PLZ test pass

2019-11-27 19:49 UTC, DeseineClement requested changes

2019-11-27 19:49 UTC, DeseineClement commented on app/Http/Controllers/Api/NewsletterController.php
> +    private function bindNewsletterAndArtwork($artworkIds, $newsletter, $user)
you sure you want to pass an array in a route ?

2019-11-27 19:49 UTC, DeseineClement commented on app/Http/Controllers/Api/NewsletterController.php
> +            if (is_null($artwork) || ($artwork->gallery->id != $user->gallery->id)) {
use Isset instead

2019-11-27 19:49 UTC, DeseineClement commented on app/Http/Controllers/Api/NewsletterController.php
> +        $customer = $newsletter->customers()->get()[0];
why not using first() instead ?

2019-11-27 19:49 UTC, DeseineClement commented on app/Http/Controllers/Api/UserController.php
> +
Ahah nope.
Please remove your comments

2019-11-28 18:18 UTC, CorvinAlex commented on app/Http/Controllers/Api/NewsletterController.php
> +    private function bindNewsletterAndArtwork($artworkIds, $newsletter, $user)
Yes

2019-11-28 18:18 UTC, CorvinAlex commented on app/Http/Controllers/Api/NewsletterController.php
> +            if (is_null($artwork) || ($artwork->gallery->id != $user->gallery->id)) {
done

2019-11-28 18:18 UTC, CorvinAlex commented on app/Http/Controllers/Api/NewsletterController.php
> +        $customer = $newsletter->customers()->get()[0];
done

2019-11-28 18:18 UTC, CorvinAlex commented on app/Http/Controllers/Api/UserController.php
> +
done

2019-11-28 18:18 UTC, DeseineClement commented on app/Http/Controllers/Api/NewsletterController.php
> +    private function bindNewsletterAndArtwork($artworkIds, $newsletter, $user)
ok

2019-11-28 18:19 UTC, merged